import Navbar from "./components/layout/Navbar";
import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import { getLangFromCookieUtils } from './utils/getLangFromCookieUtils';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const lang = getLangFromCookieUtils();

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar language={lang} />
        {children}
      </body>
    </html>
  );
}
